name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/metrics.yml"

jobs:
  isometric-calendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate full-year isometric calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: allenchenhan99
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
